libs/EleCa/include/EleCa/Particle.h
libs/EleCa/src/EnergyLoss.cpp
libs/EleCa/src/Particle.cpp
libs/EleCa/src/Propagation.cpp
src/PhotonPropagation.cpp

various bugfixes and generation function for Eleca particle.

Photon bugfixes

---

CMakeLists.txt
include/crpropa/PhotonBackground.h
include/crpropa/module/EMDoublePairProduction.h
include/crpropa/module/EMInverseComptonScattering.h
include/crpropa/module/EMPairProduction.h
include/crpropa/module/EMTripletPairProduction.h
python/2_headers.i
src/PhotonBackground.cpp
src/module/EMDoublePairProduction.cpp
src/module/EMInverseComptonScattering.cpp
src/module/EMPairProduction.cpp
src/module/EMTripletPairProduction.cpp

Added modules for PP, DPP, ICS, TPP process.
Added URB Protheroe96 model to photon backgrounds.

Inclusion EleCa in CRPropa

---

src/module/EMDoublePairProduction.cpp
src/module/EMInverseComptonScattering.cpp
src/module/EMPairProduction.cpp
src/module/EMTripletPairProduction.cpp

- Internal tabulation of dSigma/dx CDF
- Smearing of tabulated s_kin values from interactionrate CDF within right binsize

Several fixes for EM cascading

---

src/PhotonPropagation.cpp

- Fixed energy binning
- Fixed that particles at observer (d = 0 Mpc) are accidentally propagated

DINT Propagation Fixes

---

include/crpropa/Source.h
src/Source.cpp
test/testSource.cpp

Here is the revised version of the SourceSNRDistribution class.
I hope that I implemented all your comments correctly.

Improvement of SourceSNRDistribution

---

test/testDiffusionSDE.py.in

Changed the critical values for the automated python test of the DiffusionSDE module. Now they are more robust and cause less likely a failure of the travis test.

Robust testing

---

include/crpropa/Source.h
src/Source.cpp

A new source class using the Pulsar distribution given in Faucher‐Giguere, Claude‐Andre
Kaspi, Victoria M., ApJ **643** (2012) 332-355.
If anyone has a good idea for a meaningful test case I will be happy to include it.

SourcePulsarDistribution

---

include/crpropa/module/PhotonOutput1D.h
src/module/PhotonOutput1D.cpp

Updates on 1D photon output. Added 'gzip' functionality. Added one line to output, the source distance, allowing for reweighting to different source evolutions.

Updates on 1D photon output

---

include/crpropa/Grid.h
src/GridTools.cpp
src/Source.cpp
test/testCore.cpp

I changed the spacing of a grid from one double to a Vector3d. Now are grids with different spacing along the axis suported.

Vector spacing for Grid

---

src/module/PhotoPionProduction.cpp

This pull request aims to resolve issue #225.
Changes occur in the `PhotoPionProduction.cpp` file in the treatment of secondary particles after SOPHIA has been called. In order to reduce the amount of extra run time needed, the code makes the following approach:
1) The outgoing particles from SOPHIA are being looped over as before, yet each proton and neutron (particle IDs 13 and 14) are not being added as secondaries directly. Their type (proton or neutron) and energy are being stored in two separate vectors `pnType` and `pnEnergy` and no secondary is being generated in this case, nor is the canditate's energy being modified. Particles that are not protons or neutrons are being treated as they were before.
2) The maximum energy of all outgoing protons and neutrons is searched in …

bugfix PhotoPionProduction resolving issue #225

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/problems-installing-crpropa.md

As discussed during the developer meeting. These templates may in particular help reducing the installation requests.

Created issue templates

---

CHANGELOG.md
CMakeLists.txt

Just cosmetics from the release branch.

Update changelog + bump version number

---

python/2_headers.i

getSeed, getSeedThreads returns now list of ints instead of swig object.

Provide access to random seeds from python, Closes: #233

---

CHANGELOG.md
CMakeLists.txt

CMake 3 is required  for C++11; see also discussion here https://github.com/CRPropa/CRPropa3/commit/12e581deb06c9072c02cef95f3fab9a94a441385#commitcomment-37056269

Check for CMake > 3

---

.travis.yml

Forgot to add the key to the ssh-agent

Fixed travis auto deploy of webpage

---

.travis.yml

Looks like the `wheel` package is missing. Trying with pip install...

Trying to fix make doc, v2

---

CHANGELOG.md
CMakeLists.txt

Update master after 3.1.7 release.

Post-release (3.1.7) development version

---

src/magneticField/turbulentField/PlaneWaveTurbulence.cpp

Hi, so recently I was going through the implementation for PlaneWaveTurbulence again, and I noticed that some of the comments had become outdated, or had room for improvement otherwise. I just went through and improved some of them a bit, and also deleted some code that was no longer used.
I'm not done with this yet, but I wanted to open a PR to let you know that I'm looking at this, and to give you the opportunity to add your own suggestions. (Or to tell me that I shouldn't be working on this because it's not that important.)
Anyway, feel free to chime in if you want. I'd like to keep this PR small (there might be more things to discuss but I'd prefer keeping this one focused on just the comments), since I'm somewhat busy right now and my energy for this is limited. In particular, it …

Improve comments for the plane wave turbulence code

---

doc/pages/Basic-concepts.md
doc/pages/example_notebooks/Diffusion/DiffusionValidationI.v4.ipynb
doc/pages/example_notebooks/acceleration/first_order_fermi_acceleration.ipynb
doc/pages/example_notebooks/acceleration/second_order_fermi.ipynb
doc/pages/example_notebooks/density/densitys_easy_example.ipynb
doc/pages/example_notebooks/galactic_trajectories/galactic_trajectories.v4.ipynb
doc/pages/example_notebooks/secondaries/photons.v4.ipynb
doc/pages/example_notebooks/sim1D/sim1D.v4.ipynb
doc/pages/example_notebooks/sim4D/sim4D.v4.ipynb
src/module/NuclearDecay.cpp

This PR adds comments to the NuclearDecay module and fixes some typos in the documentation.

Miscellaneous

---

include/crpropa/Source.h
src/Source.cpp
test/testSource.cpp

Here is the second try for a PR including a new free parameter in the SNR distribution. 
Additionaly changed some coding conventions in the pulsardistribution too.

Snr distribution

---

.gitignore
README.md
doc/pages/AdditionalResources.rst
doc/pages/extragalactic-simulations.rst
doc/pages/galactic_cosmic_rays.rst

This PR mainly fixes a few broken links in the documentation.

Data download

---

CHANGELOG.md
CMakeLists.txt

This PR updates the master branch to include the changes from the 3.2.1 release and prepares the repo for new changes.

Post Release Clean Up

---

include/crpropa/magneticField/GalacticMagneticField.h

Fixed sign of logarithmically decaying magnetic field strength for LogarathmicSpiralField.
The magnetic field strength should decrease with distance from the Galactic plane.

BugFix: LogarithmicSpiralField

---

include/crpropa/magneticField/UF23Field.h

... just a small change in the comment of the header file.

update reference to GMF paper
