src/module/PropagationCK.cpp
bug fix: h [time] was compared to minStep [length]. Fixed units.
=> Wrong unit comparison in PropagationCK::process

src/Candidate.cpp
Using the new interpolated position of the secondary particle, the trajectory length became too long. Therefore, the trajectory length was changed using the difference of the interpolated position and the current position. So, this commit is supposed to fix the problem.
=> Secondary trajectory length

test/python/testJF12Field.py
Change order of x and y to get right rotation in field, change axis labels
=> Fix for JF12 field slice example 

src/module/EMDoublePairProduction.cpp, src/module/EMInverseComptonScattering.cpp, src/module/EMPairProduction.cpp, src/module/EMTripletPairProduction.cpp
use scaling for interaction rate instead of scaling for energy loss rate
=> Fixed cosmological scaling

include/crpropa/Source.h, src/Source.cpp, test/testSource.cpp
Add a simple source class for drawing source positions from the Galactic SNR distribution. For details of the distribution see G. Case and D. Bhattacharya, _Revisiting the galactic supernova remnant distribution_, Astron.& Astroph. Suppl. **120** (Dec., 1996)
=> Add source class: SourceSNRDistribution

src/Source.cpp
Test-Script:
from crpropa import *
d=1.
source = SourceUniformShell(Vector3d(50.)*Mpc, d * Mpc)
can = Candidate()
canPos = can.current
can = Candidate()
canPos = can.current
source.prepareParticle(canPos)
Pos = canPos.getPosition()
print Pos/Mpc, (Pos/Mpc-Vector3d(50.)).getR()
=> Fix the bug in SourceUniformShell. Now the center of the shell is taken into account

include/crpropa/Variant.h, include/crpropa/module/HDF5Output.h, include/crpropa/module/Output.h, python/2_headers.i, src/Variant.cpp, src/module/HDF5Output.cpp, src/module/Output.cpp, src/module/TextOutput.cpp, test/testCore.cpp, test/testOutput.cpp
Candidate properties can be added to Text and HDF Output as follos:
```python
import crpropa
output1 = crpropa.HDF5Output('test.h5')
output2 = crpropa.TextOutput('test.txt')
output1.enableProperty('bool', False, "Foo Bar Spam and Eggs")
output1.enableProperty('int', 23)
output1.enableProperty('float', 42.23)
output1.enableProperty('string', "WTF") # For strings the default value defines the maximum size of the string in HDF5!
output2.enableProperty('bool', False, "Foo Bar Spam and Eggs")
output2.enableProperty('int', 23)
output2.enableProperty('float', 42.23)
output2.enableProperty('string', "WTF") 
c = crpropa.Candidate()
for i in range(5):
c.setProperty('int', i+12)
output1.process(c)
output2.process(c)
output1.close()
output2.close()
```
=> Add candidate properties to output files

CMakeLists.txt, include/crpropa/Random.h, include/crpropa/base64.h, include/crpropa/module/TextOutput.h, src/Random.cpp, src/base64.cpp, src/module/HDF5Output.cpp, src/module/NuclearDecay.cpp, src/module/PhotoDisintegration.cpp, src/module/PhotoPionProduction.cpp, src/module/TextOutput.cpp, test/testCore.cpp
These changes handle storing the random seed with aim to ease reproducibility of rare errors
* Seed is stored in hdf5 files per default
* Seed is stored in TextOutput if enabled
* Seed is printed in error stream on runtime_error in some interactions
=> Store random seed, Closes: #190

src/Random.cpp
During recent attempts to simulate ultra-narrow CR jets, I was stung by the computational cost of `randConeVector`. Since `randConeVector` uses rejection sampling across the entire unit sphere it is extremely inefficient with small angular sizes and made my studies of ~1 arcsecond jets completely intractable. 
Picking a polar angle on the surface of a unit sphere within some range is analytically calculable and this pull-request implements that solution. I also wrote a testbench (attached below) that shows that the two solutions agree to within one part in a million for my limited statistics run (this will improve with additional statistics).
For a ~1arcsecond half-width, the analytical solution is six orders of magnitude faster than rejection sampling (calculated by timing 10,000 …
=> Added analytic spherical point picking for randConeVector

CMakeLists.txt
This is a temporary workaround for issue #244: 
With this option kwargs are curerrntly silently ignored. This is
probably a SWIG bug https://github.com/swig/swig/issues/1595
=> disable swig -builtin as default

.gitignore, include/crpropa/Random.h, include/crpropa/Source.h, include/crpropa/Vector3.h, src/Random.cpp, src/Source.cpp
Addresses issue #246, the user is now able to setup an isotropic galactic arrival scenario:
```
source = crp.Source()
source.add(crp.SourceIsotropicGalacticArrival(crp.Vector3d(0, 0, 0) * crp.kpc, 20 * crp.kpc))
```
You can test it by run the provided script in issue #246 and replace the 
```
source = crp.Source()
source.add(crp.SourceUniformShell(crp.Vector3d(0, 0, 0) * crp.kpc, 20 * crp.kpc))
source.add(crp.SourceIsotropicEmission())
```
by the above code block. I put the observer more outside (15 kpc instead of 8.5 kpc) of the center to make the anisotropies visible also with lower statistics. You should be able to run it on your local PC within 2 minutes. 
I hope the new function will prevent more future publications about the violation of Liouville...
=> Implement Lamberts distributed vectors and an isotropic arrival scenario at the edge of the Galaxy

include/crpropa/module/BreakCondition.h, src/module/BreakCondition.cpp, test/testBreakCondition.cpp
**What's new?**
Adds a new break condition based on the charge number of the candidates.
**Use case**
I was using this feature for a study on the propagation distance of different elements. I did not want to use the minimum energy break condition. With this break condition I was able to get rid of low charge number candidates that I was not interested in.
=> Break condition: charge number

src/module/PhotoPionProduction.cpp
Should resolve #254 
@Froehliche-Kernschmelze have you encountered this?
=> Add a check for CMB field before deactivating the the redshift evolution

CHANGELOG.md, include/crpropa/Vector3.h
This fixes an increase of the memory footprint of the Vector3 implementation using public references. Credits for finding this elegant solution go to Andrej Dundovic.
I checked that the solution also works on intel compiler.
=> Fix increased memory footprint of Vector3

CMakeLists.txt, include/CRPropa.h, include/crpropa/magneticField/TF17Field.h, python/2_headers.i, src/magneticField/TF17Field.cpp
Dear all,
In this pull-request, I want to provide the implementation of the Galactic and halo magnetic field presented in [Terral & Ferrière 2017](https://ui.adsabs.harvard.edu/abs/2017A%26A...600A..29T/abstract).
I implemented all 6 models of the paper: disk (Ad1, Bd1, Dd1) + halo (C0, C1).
The models can be set as follow :
```python3
disk_model = "Ad1"
halo_model = "C0"
GMF = crpropa.TF17Field(disk_model,halo_model)
```
The field at a given position can be call as usual:
```python3
B = GMF.getField(crpropa.Vector3d(0,0,0))
```
All models have been checked by Katia Ferrière. As far as I know, the implementation is correct.
I would like to point out that from the few tests I made, the models have some problems. The Faraday rotation is indeed only fittted in the halo (excluding the …
=> Implementation of Terral and Ferrière 2017 Galactic magnetic field

CHANGELOG.md, include/crpropa/magneticField/JF12Field.h, src/magneticField/JF12Field.cpp
Implements a variant of the JF12 field from the Planck collaboration following arXiv:1601.00546 with changed parameters only. Mikhail Zotov send me this parameters in a private mail. He used them for a recent publication. I verified that the parameters match with the values in arXiv:1601.00546 .
=> Add JF12b variant of JF12 field.

include/crpropa/Grid.h, include/crpropa/GridTools.h, include/crpropa/GridTurbulence.h, include/crpropa/Source.h, include/crpropa/magneticField/JF12Field.h, include/crpropa/magneticField/MagneticFieldGrid.h, python/2_headers.i, src/GridTools.cpp, src/GridTurbulence.cpp, src/Source.cpp, src/magneticField/JF12Field.cpp, src/magneticField/MagneticFieldGrid.cpp, test/testCore.cpp, test/testMagneticField.cpp
I want to introduce double-precision grids in CRPropa as an option. Corner cases do exist where single-precision is not enough (especially in simulations where coupling between magnetic fields and particles are "strong", i.e., in the diffusive regime) and that can affect physical results. Before, I did this as a special CMake option with which one can recompile the source and make all grids in double-precision. Now I think it is a wrong approach, on the top of the fact that it is ugly too (I let CMake to change source files, i.e., Grid.h, which makes the whole process of compiling more complex and harder to debug).
This PR removes the changes of the previous approach and introduces single- and double-precision grids that can be used in parallel. Moreover, no new options in CMake neither …
=> Double precision grids

CMakeLists.txt, include/crpropa/module/BreakCondition.h, include/crpropa/module/Observer.h, src/module/BreakCondition.cpp, src/module/Observer.cpp, test/testBreakCondition.cpp
- Allows user-written plugins to access the googletest suite by installing them.
- Provides functionalities to apply a minimum energy break condition for specific types of particles (useful for CR-induced cascades, for example).
The name MinimumEnergyParticle is probably not the best, but I couldn't think of anything better than this... or MinimumEnergySpecificTypesOfParticles.
=> Minimum energy for specific types of particles

.travis.yml
I think that coverage reports are rarely (if ever?) used when people (including CRPropa developers) compile the code offline since it is slowing down the compilation and an additional flag in CMake has to be turned on. Thus, I propose with this PR that we introduce automatic coverage which will be executed by TravisCI and pushed to free-for-free-software service Coveralls.io. This will be integrated with the GitHub workflow and advise all of us that we need to cover the code with tests. Consequently, the quality of the code will be higher.
=> Automatic coverage reports through coveralls.io service

include/crpropa/Source.h, src/Source.cpp, test/testSource.cpp
Implement normalization of the direction vector.
When used with very large numbers the SourceEmissionCone source feature would deliver sometimes NANs in the prepared particle direction. 
This bug(?) was found by @JonPaulLundquist. I could reproduce it with the attached script and solved the issue by implementing a normalization routine for the source feature. A simple test was added additionally.
`from crpropa import *`
`direction = Vector3d(1e20, -2e22, 1e21)`
``
`s = Source()`
`s.add(SourceParticleType(nucleusId(1, 1)))`
`s.add(SourceEmissionCone(direction, 0.1))`
``
`while True:`
`Dir = s.getCandidate().source.getDirection()`
`    if Dir.x != Dir.x:`
`        print Dir`
`        break`
=> Improvement SourceEmissionCone:

.travis.yml, CHANGELOG.md, CMakeLists.txt, doc/pages/Data-files.md
This is just a small change in `CMakeLists.txt` to accommodate PR #286: **data.tar.gz** becomes **data-`date +"%Y-%m-%d"`.tar.gz**. I've put also a copy of the current `data.tar.gz` at our DESY [data download path](https://www.desy.de/~crpropa/data/interaction_data/).
=> Basic file versioning of the data archive in CMakeLists.txt

CHANGELOG.md, CMakeLists.txt, doc/building_blocks.rst, doc/buildingblocks/PhotonFields.rst, include/crpropa/PhotonBackground.h, include/crpropa/module/EMDoublePairProduction.h, include/crpropa/module/EMInverseComptonScattering.h, include/crpropa/module/EMPairProduction.h, include/crpropa/module/EMTripletPairProduction.h, include/crpropa/module/ElasticScattering.h, include/crpropa/module/ElectronPairProduction.h, include/crpropa/module/PhotoDisintegration.h, include/crpropa/module/PhotoPionProduction.h, python/2_headers.i, src/PhotonBackground.cpp, src/module/EMDoublePairProduction.cpp, src/module/EMInverseComptonScattering.cpp, src/module/EMPairProduction.cpp, src/module/EMTripletPairProduction.cpp, src/module/ElasticScattering.cpp, src/module/ElectronPairProduction.cpp, src/module/PhotoDisintegration.cpp, src/module/PhotoPionProduction.cpp, test/testInteraction.cpp, test/testSimulationExecution.py
Hi everyone,
as we had discussed previously, the way of how photon fields are implemented in CRPropa needs an overhaul and where reasonable should converge towards the user-concept of magnetic fields. It is also mandatory for variable photon fields to be introduced although this PR constrains itself to the currently available photon fields.
This PR should provide an advanced draft of how such an implementation could look like. The main features are:
1) A user can call a PhotonField object in the steering file, modify it, and pass it to an interaction module as it is currently possible with B-fields. An example of how this looks like is
```
CMB = PhotonField("CMB")
ppp = PhotoPionProduction(CMB)
```
2) Interaction modules infer most photon field data from this PhotonField class. This …
=> introduce proper photon field class

doc/pages/example_notebooks/advanced/CustomObserver.v4.ipynb, doc/pages/example_notebooks/extragalactic_fields/MHD_models.v4.ipynb, doc/pages/example_notebooks/galactic_backtracking/galactic_backtracking.v4.ipynb, doc/pages/example_notebooks/propagation_comparison/Propagation_Comparison_CK_BP.ipynb, doc/pages/example_notebooks/sim4D/sim4D.v4.ipynb, doc/pages/example_notebooks/trajectories/trajectories.v4.ipynb, include/crpropa/magneticField/turbulentField/SimpleGridTurbulence.h
Just a fix of my mistake in which the s(pectral) index ("5/3") is replaced with the alpha index ("-11/3") in the correlation length expression for `SimpleTurbulenceSpectrum`. I also updated docs to use `Grid3f` instead of `VectorGrid`.
=> Fix in simplegridturbulence

src/PhotonPropagation.cpp
I know DINT is probably on its way out, but right now it crashes for me. 
This commit fixes it (the size check is in the wrong place here, and trying to access .back().X1 on a zero-size vector triggers a segfault for me, although I guess it can also fail silently).  The second check is probably extraneous but I fixed it anyway.
=> fix segfault in DintPropagation due to size check in wrong place

.travis.yml
Looks like an error in a new version of Ubuntu - missing the wheel package:
```
...
Running setup.py bdist_wheel for m2r: finished with status 'error'
Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lgreiffg/m2r/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp__bo87sypip-wheel- --python-tag cp36:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help
error: invalid command 'bdist_wheel'
```
=> Trying to fix make doc

src/massDistribution/ConstantDensity.cpp, src/massDistribution/Cordes.cpp, src/massDistribution/Ferriere.cpp, src/massDistribution/Nakanishi.cpp
@avvliet found that a lot of KISS warnings are raised, when he tested the massDistribution examples. 
This was related to a bug in the implementation of the check if a warning should be raised. Now the KISS warning is raised when one or more components (HI, HII, H2) of the gas distributions is available but *not* activated. The option to deactivate individual components was implemented to allow for combinations of several gas distribution models. 
Furthermore, some typos were fixed and the formatting of the warnings and the getDescription method updated.
=> Fix KISS Warnings in gas density classes

src/magneticField/JF12Field.cpp
Besides just replacing the code, I've named turbulent field parameters for readability:
```c++
const double lMin = 8 * parsec;
const double lMax = 272 * parsec;
const double Brms = 1;
const double spacing = 4 * parsec;
const double grid_n = 256;
auto spectrum = SimpleTurbulenceSpectrum(Brms, lMin, lMax);
auto gp = GridProperties(Vector3d(0.), grid_n, spacing);
auto tf = SimpleGridTurbulence(spectrum, gp, seed);
```
In addition, a few trivial tests checks if the output field remains the same.
=> Fix #338, removes deprecation warning due to initTurbulence in JF12

CMakeLists.txt, src/module/PhotoPionProduction.cpp
This PR should fix the issue brought up in #340.
The issue was twofold:
1) Some tables (interaction rates for redshift independent photo pion production on the EBL) were not correctly copied from version 3.1.6 to version 3.1.7.
2) The check for the CMB target photon field (in PhotoPionProduction) was not implemented correctly.
@Leander Schlegel from Ruhr University Bochum did quite some checks to pin down this problem and confirms that the version of this PR yields the same PPP secondaries as version 3.1.6.
=> Fix photon field

CMakeLists.txt
When data tar balls, including a date signature, were introduced in 957bdae, the new data structure was not consistently used in the install part of the CMakeList file. This PR updates the install path.  
This should fix issue #354.
=> Update share directory of interaction data

include/crpropa/module/DiffusionSDE.h, include/crpropa/module/PropagationBP.h, include/crpropa/module/PropagationCK.h, python/2_headers.i, src/module/DiffusionSDE.cpp, src/module/PropagationBP.cpp, src/module/PropagationCK.cpp, test/testPythonExtension.py
This PR fixes #365. Currently, CRPropa can't handle custom magnetic fields implemented in Python. This PR allows for custom magnetic fields via Python.
**Background**
To correctly implement a Python class that inherits from the wrapped C++ MagneticField class that contains virtual methods, cross-language polymorphism via directors is needed. The child Python class for the custom magnetic field should override the getField base class function. However, as we don't have enabled directors for the MagneticField class, this fails currently.
**Changes**
Inserting the decorator in the `2_headers.i` file solves the issue. For enhanced testability and synchronization between the propagation modules, I introduced getField functions for PropagationCK and DiffsuionSDE, similar to PropagationBP. I …
=> Custom magnetic fields via Python

python/1_swig.i, python/4_lens.i, test/testMagneticLensPythonInterface.py
This PR fixes #350. The tests for the magnetic lenses were failing in some cases. 
It was tested in OSX 11.4 and on Cent OS, both with  Python 3.8.3. More tests might be needed.
This quick fix draws largely from the suggestions by user @tdwiser [33631c8](https://github.com/tdwiser/CRPropa3/commit/33631c8abb3f9a93e8ef8ef6422cf7e528db8e14) suggested in #350. This might also be relevant for issue #316.
=> Fix magnetic lenses test

src/EmissionMap.cpp, src/PhotonPropagation.cpp, src/module/EMCascade.cpp, src/module/PhotonEleCa.cpp
This simple pull request adds deprecration warnings to calls to both DINT and EleCa.
Additionally, it changes a std::cout warning message in `EmissionMap.cpp` to a kiss warning.
=> Deprecate DINT/EleCa

CHANGELOG.md, CMakeLists.txt, include/CRPropa.h, include/crpropa/magneticField/PolarizedSingleModeMagneticField.h, python/2_headers.i, src/magneticField/PolarizedSingleModeMagneticField.cpp, test/testMagneticField.cpp
This contribution adds the possibility of defining a magnetic field with a single polarization mode in CRPropa. This includes the more specific circular and linear polarizations, but also the more general elliptical one, as well as a formalism to handle magnetic helicity.
=> Implementation of the new PolarizedSingleModeMagneticField class (new)

CMakeLists.txt, src/PhotonBackground.cpp
This PR updates the data download to a new version (data-2021-11-25).
This data is reproducible with the current version of the crpropa-data repository. All files include now information in the header that specifies the git hash of the crpropa-data repository that was used to create them
This made small changes in CRPropa's files readers necessary. 
Furthermore, this PR improves the CRPropa internal calculation of the redshift scaling of photon target fields.
=> Update CRPropa download data

include/crpropa/magneticField/turbulentField/SimpleGridTurbulence.h, include/crpropa/magneticField/turbulentField/TurbulentField.h, src/magneticField/turbulentField/GridTurbulence.cpp, src/magneticField/turbulentField/PlaneWaveTurbulence.cpp
Dear all,
with this pullrequest we want to provide a fix to the issue of the non-uniform spectral index handling, as described in #387.
Analyzing the problem, we made two changes:
First, to solve the problem for the PlaneWaveTurbulence method using SimpleTurbulenceSpectrum that was shown in #387, we effectively removed the "+1" in the exponent in the denominator of the formula of the power spectrum, to be accordant to the Tautz and Dosch 2013 paper, as suggested in the discussion of the issue.
Second, we found that for a uniform handling, it would be good to also change the argument that is given to energySpectrum() in the general case of TurbulenceSpectrum. Instead of giving it k^ = k * l_bendover, we put the multiplication with the bendoverscale inside of the function to have the same …
=> Uniform interface for the turbulence generation

include/crpropa/Grid.h, include/crpropa/module/Observer.h, src/module/Observer.cpp, test/testBreakCondition.cpp
Dear all,
with this pull request, I want to provide the possibility to use a logarithmic scaling of the ObserverTimeEvolution, which is especially useful if you want to resolve different time scales in your simulations. The feature has proven useful in numerous studies (running diffusion coefficients, lightcurves in sources, ...) over the past few years, which is why I'd like to share it. 
The functionality of the linear observer remains unchanged:
`ObserverTimeEvolution(min, dist, numb)`
With constructor overloading, I implemented the log-scaling in analogy to numpy.logspace:
`ObserverTimeEvolution(min, max, numb, True)`
Test to verify the feature are implemented.
Best,
Patrick
=> Log observer time evolution

.github/workflows/testing.yml, .github/workflows/testing_OSX.yaml, .github/workflows/testing_ubuntu22.yml
This PR updates the automated tests to more recent ubuntu versions. Ubuntu-22 is now included in the test matrix.
The Ubuntu-18 test will only work until 2023-04-01. However, I kept it in the test until then as some people are still using ubuntu-18.
I was not able to update to macos-12. So I removed it again from the mac test matrix. Maybe @rafaelab can at some point help with updating the test.
Also some of the github actions are updated.
Tests should now also be triggered for a PR and not only for a push. --> We get the test results before merging into master.
=> Update testing environments

src/magneticField/JF12Field.cpp
The KISS warnings should be raised if the turbulent component is **not** available.
=> Fix check for turbulent field components

include/crpropa/module/PropagationBP.h, src/module/PropagationBP.cpp, test/testPropagation.cpp
**Description**
This pull request improves the behavior of the PropagationBP module in CRPropa for fixed step sizes, resulting in a speed improvement of up to a factor of 3. In addition, I have implemented a test to verify the correct behavior of my changes in the module. I also manually checked the output files and compared them to the current master.
**Performance comparison**:
simulation time with grid-less turbulence:
master:  75.05±0.11 s
this PR:  25.43±0.02 s
simulation time with grid turbulence:
master:  82.04±0.23 s
this PR:  57.16±0.22 s
_Code to reproduce_:
```
import crpropa as crp
sim = crp.ModuleList()
turbulence_method = 'PW' # or 'grid'
b_field = crp.MagneticFieldList()
turbulence_spectrum = crp.SimpleTurbulenceSpectrum(1e-6*crp.gauss, crp.pc, 100*crp.pc)
if …
```
=> Improved performance of PropagationBP

CHANGELOG.md, include/crpropa/Grid.h, test/testCore.cpp
This PR adds a default value for the volume clipping switch to the `GridProperties` module.
Context:
Creating a grid (e.g. `Grid3f`) is possible in different ways. Either grid properties can be defined as separate arguments or a GridProperties instance is used as a single argument for the Grid constructor. 
However, the handling to define the clipVolume value was different depending on the chosen constructor. This behavior is unified by this PR and defaults now to `clipVolume=false` for all Grid constructors. 
Issue:
Using the Grid constructor with the GridProperties argument led to a random initialization of the clipVolume variable.
Problem:
This might have led to an unnoticed effect, e.g. in turbulent magnetic field creation, where the field strength outside the original grid volume …
=> GridProperties: Default Value for Volume Clipping

test/testCore.cpp
This PR updates the comparison function to EXPECT_FLOAT_EQ instead of EXPECT_EQ for Grid1f tests. The latter one led to failing test on some architectures. 
Thanks to Roark Habegger from UW Madison for finding this bug.
=> Fix testCore: Float comparison for Grid1f tests

include/crpropa/Source.h, src/Source.cpp
This PR introduces changes to the SourceDirectedEmission() module.
The SourceDirectedEmission() module samples a random vector from the von Mises-Fischer distribution defined by a mean direction and a concentration parameter. This vector is then used for the injection of the candidate. The sampling was done as in http://people.csail.mit.edu/jstraub/download/straub2017vonMisesFisherInference.pdf .
Given the presence of a function for random sampling from a von Mises-Fischer distribution (in Random.cpp), the sampling procedure was modified. Some functions in the module are no longer needed.
Thanks to @avvliet for help with the changes and with the PR.
=> Improvemente of Directed Emission Module

src/module/Output.cpp, test/testOutput.cpp
as discussed in #428 the `CandidateTagColumn` should not be part of the `EventND` Output fortmat. 
I added the tag for the `printHeader_custom` test of the textoutput, to have at least one test including the column.
=> remove candidate tag column from EventND output type

include/crpropa/advectionField/AdvectionField.h, src/advectionField/AdvectionField.cpp
This PR adds new shock profiles for simulating diffusive shock acceleration to the AdvectionField module. In the 2023 ICRC proceedings the advection field `OneDimensionalAdvectionShock` was used to obtain the time-dependent spectra at a 1D cartesian shock. Additional shock profiles allow for oblique shocks and 1D radial shocks.
=> New advection fields

CMakeLists.txt, include/CRPropa.h, include/crpropa/module/CandidateSplitting.h, python/2_headers.i, src/module/CandidateSplitting.cpp, test/testCandidateSplitting.cpp
This pull request adds a new module that splits candidates in a user-defined number of copies when energy boundaries are crossed. The candidates weights are lowered depending on the splitting number. Candidates can be split until a minimal weight is reached. To use, the `CandidateSplitting` module must be added to the `ModuleList`.
Originally, the module was developed to enhance statistics at high energies for diffusive shock acceleration. For that, only the expected spectral index, minimal energy and number of energy bins needs to be specified. The energy bins are then calculated so that the decrease of candidates over the specified energy range is compensated by always splitting into two copies. This way of splitting was used in the 2023 ICRC proceedings to model time-dependent …
=> Candidate Splitting module

include/crpropa/Variant.h, src/Candidate.cpp, src/Variant.cpp, src/module/TextOutput.cpp, test/testCore.cpp
This PR improves the handling of variants in CRPropa. It updates the previous implementation making the code more efficient. Its main goal is to facilitate the lives of users aiming to write their own plugins. 
This PR also adds some more tests in `testCore.cpp` to check if variants are being treated correctly.
Currently some types like `Vector3d` cannot be treated as a variant. Instead, the user would require three `double` and consequently three operations to handle it.
New types added are: `complex<double>`, `complex<float>`, `Vector3d`, `Vector3f`, `Vector3c` (alias for `Vector3<complex<double>>`, `long double`. A new type for a vector of variants (`vector<Variant>`) was also added.
For some yet-unknown reason these new types have to be called with `variant.toVector3d()`, for …
=> Variant improvements

CHANGELOG.md, CMakeLists.txt, include/crpropa/PhotonBackground.h
This PR adds the recent [Saldana-Lopez 2021](https://ui.adsabs.harvard.edu/abs/2021MNRAS.507.5144S/abstract) EBL model - along with its lower and upper limits - to CRPropa. The model data files are part of the [related PR](https://github.com/CRPropa/CRPropa3-data/pull/18) to the CRPropa-data repository.
=> Saldana-Lopez 2021 EBL model

CMakeLists.txt
With this PR the `ENABLE_QUIMBY` flag in the installation is set to `OFF` as default. 
In many cases Quimby is not used for simulations and therefore users needing Quimby should activate it in the installation
=> remove Quimby from default installation

doc/pages/AdditionalResources.rst, doc/pages/Data-files.md, doc/pages/example_notebooks/density/density_grid_sampling.ipynb
This PR updates the links for additional resources to download data from RUB's sciebo instead of the hard to maintain DESY cloud. Closes #454.
=> Update download links

.github/workflows/test_examples.yml, CMakeLists.txt
I noticed a problem with the new installation in the example-test. In the previous test we had no write access to the package installation directory. I addepted it to the `.local` folder. 
Also I added the `Python_INSTALL_PACKAGE_DIR` as an option when using `ccmake`
=> add python_install_package as ccmake option, adapt example test

.github/workflows/create_documentation.yml
Due to the change of installation the change in building the documentation is needed. 
With this PR we also move from Node 16 to Node 20 (see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) by updateing the versions of the used actions (checkout and upload-artifact).
=> Update action to create the documentation

doc/pages/Installation.md
Minor changes to the documentation to reflect the recent updates.
=> updated doc for new Python interface via cmake

.github/workflows/create_documentation.yml
The `lxml` package, used to build the documentation, has been restructured. (See https://sources.debian.org/src/lxml/5.2.0-1/PKG-INFO/?hl=83#L83) 
Therefore we have to install the `lxml[html_clean]` package seperatly.
=> Automatic documentation build

CHANGELOG.md, include/crpropa/ParticleMass.h, src/ParticleMass.cpp, src/ParticleState.cpp, test/testCore.cpp
Dear all,
with this PR we try to fix #483. @lukasmerten, @JulienDoerner and me discussed it and introduced a new function particleMass(int id) in ParticleMass.cpp to fix the bug by calling it in setId(int newId) in ParticleState.cpp. It gives all particles other than nuclei or electrons/positrons a zero rest-mass and could possibly be extended for other particles when needed.
=> Possible fix for wrong secondary masses of photons and neutrinos

include/crpropa/Referenced.h, src/Candidate.cpp, src/module/HDF5Output.cpp, src/module/OutputShell.cpp, src/module/ParticleCollector.cpp, src/module/PhotoPionProduction.cpp, src/module/PhotonOutput1D.cpp, src/module/TextOutput.cpp, src/module/Tools.cpp
Dear All,
with this pull request I want to add names to various `#pragma omp critical` statements.
If such a statement has no name, it blocks every other critical statement with no name, which may cause an increase in runtime.
For example, a shell output should only block other shell outputs and not file outputs.
Furthermore, if not accessed through a python script but directly through c++, critical statements from the users files may also block critical statements in CRPropa.
=> Add names to omp critical statements

src/module/EMDoublePairProduction.cpp, src/module/EMInverseComptonScattering.cpp, src/module/EMPairProduction.cpp
Dear all,
@lukasmerten , @JulienDoerner and me discussed a possible fix of #488 and thought of opening this very small PR. 
We switched the order of the lines in EMPairProduction.cpp that in the current master-version would prevent the catastrophic energy loss of the pairproduction in the case of haveElectrons=False.
We also noticed two very small optimizations that could be done in EMDoublePairProduction.cpp and EMInverseComptonScattering.cpp that we included in this PR, that do not affect the physics and could lead to a little speedup in the runtime of the modules.
Thank you in advance!
=> Small fix for EMPairProduction when haveElectrons=False and small Optimizations

include/crpropa/Module.h, include/crpropa/module/Observer.h, src/Module.cpp, src/Variant.cpp, src/module/Observer.cpp
fixes #493: 
The `abstractConditions` added a property to the candidate on the rejection. Up to now it only adds the key `Rejected`. I added the module name as the default Value for the flag. 
Also the variant (in which this key is stored), does not have the right destructor. If it is deleted, the type of the variant was not passed to the `clear` function. Therefore no deletion of the variant was possible. This leaded to the bug in the memory consumption.
=> Memory management in Variants

.github/workflows/testing_OSX.yml, include/crpropa/ModuleList.h, src/ModuleList.cpp.in
I recently had a problem installing the lastest master version of CRPropa on my M1Max, this seemed to be coming from a bad include statement in ModuleList.cpp.in
`#include <bits/stdc++.h>`
This seems to be bad practice according to [this](https://stackoverflow.com/questions/31816095/why-should-i-not-include-bits-stdc-h) stack overflow post. 
I replace the general import with explicits imports of the necessary libraries, which fixed the issue for me.
In addition I tried to fix issue #515 but was not yet successful with it.
So any input on the issue with the not working MacOS runner is appreciated.
=> MacOS install issue
